### ISSUE TITLE
Improved Website Design

### ISSUE THREAD

**Issue by philipp-spiess** [philipp-spiess/this-week-in-react#1]
https://this-week-in-react.org/ is currently pretty minimalistic. Part of this ticket is the overhaul of the landing page. My plans are as follows (although all of them are discussable):

- We can improve the contrast
- We add a subscribe form to enter the email address without having to redirect to the Mailchimp form
- We can add more news sources, like our [Telegram Channel](https://mobile.twitter.com/PhilippSpiess/status/1045992619069898752)
- It should be fully responsive and great to use on mobile phones
- We should be able to link to past issues with pagination in mind
- I like that [React Status](https://react.statuscode.com/) includes the latest newsletter directly on their website. Maybe we can do something similar? 

At the moment, the website consists of an [HTML](https://github.com/philipp-spiess/this-week-in-react/blob/master/index.html), [CSS](https://github.com/philipp-spiess/this-week-in-react/blob/master/style.css), and a [JavaScript](https://github.com/philipp-spiess/this-week-in-react/blob/master/atoms.js) file.

**Comment by harleo** [comment]
I was about to opt to work on this but I saw you want to add a responsive site generator, which would have to come before. I'll check if I can get around using Gatsby once it's pushed.

**Comment by philipp-spiess** [comment]
@harleo I don't want to make the website generator step too complex. If you can work with the existing HTML and CSS files, I will happily migrate it to the Gatsby format (which will probably be very similar anyway).

**Comment by harleo** [comment]
@philipp-spiess I was thinking more of like proper folder structure etc. which wouldn't really work before you do what Gatsby wants. I'll take a look at the design itself in the mean time.

Also regarding the Mailchimp form, you'd have to use the form builder [here](https://mailchimp.com/help/add-a-signup-form-to-your-website/).

**Comment by philipp-spiess** [comment]
@harleo Thanks ❤️ 

Yeap, right. I tried it once but the default styles where not pretty and I didn't had time to write custom CSS at this point. This is the code for the raw "unstyled" embeddable form, if someone wants to take a look:

```html
<div id="mc_embed_signup">
<form action="https://this-week-in-react.us19.list-manage.com/subscribe/post?u=155aa5558694a008de40fe987&amp;id=9921ef9d30" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address </label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_155aa5558694a008de40fe987_9921ef9d30" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
````

**Comment by harleo** [comment]
@philipp-spiess Cool, I'll use that right away. Quite tricky once a lot of people are working on adding stuff at the same time.

**Comment by philipp-spiess** [comment]
@harleo Yeah I wasn't expecting this turnout either. I'll lock the landing page and design related changes for you exclusively now. 🙂 

(No pressure though, if you don't have the time just write it here again - Thanks for your help!)

**Comment by harleo** [comment]
@philipp-spiess I can work on this in peace then ;) I'll just do what I planned and juggle the issue with Gatsby later.

**Comment by harleo** [comment]
Hey @philipp-spiess check out https://github.com/harleo/this-week-in-react/commit/46405f1596d4ecad90e1a70e7a7bb58948eb7545

There are still a few things I want to fix/add but that's where it's headed.
I'll continue working on this later today.

**Comment by philipp-spiess** [comment]
Woohoo @harleo this is already a lot easier to understand than what I have!

![screen shot 2018-10-04 at 10 41 38](https://user-images.githubusercontent.com/458591/46462685-5f39b380-c7c2-11e8-97a7-88f411c0c298.png)

I think the background is a bit too intense now though without the React logos. Do you have an idea how we can fix this? Maybe something like https://react.statuscode.com/ where we split the page vertically or by some other trick. 

Thank you so much for your help here.

**Comment by harleo** [comment]
@philipp-spiess I see what you mean. I could split it up like in your example. Do you want to have the issue list on the right then where the iphone is? The problem with that is that the page will have lots of "white-space" due to missing content which will look off on desktop screens - It'll just float there. But I can totally try that if you want it. To bring back the scattered react logos, I could also use a static background image, instead of generating them. I'll continue working on this in the evening.

**Comment by philipp-spiess** [comment]
@harleo Yeah I think we're missing the content for the split approach yet but feel free to use some mocked content instead. If it looks good, I'll make some time to to have the emails available on the website as well.

I don't really have any strong opinions for all of this. If you have something in mind, please just try it out. I'll help wherever I can. 🙂 

We can also start merging it to a different branch already if you want.

**Comment by harleo** [comment]
@philipp-spiess Alright cool. I'd suggest waiting it out until I'm satisfied with how the landing page looks. Then later make adjustments in the branch :)
