### ISSUE TITLE
Use a Static Site Generator

### ISSUE THREAD

**Issue by philipp-spiess** [philipp-spiess/this-week-in-react#3]
Right now, everything is a static `.html` file and the newsletter are generated using a simple self-made script.

It would be great if we can use a static site generator (React Static, Gatsby, Next.js) so that the code is cleaner and more structured.

It should be possible to generate issues dynamically but also to supply them as a `.html` file (for an archive if we decide to change the format).

Ideally we can pre-render all content statically such that no JavaScript at runtime is necessary.

**Comment by Apoorv-Mittal** [comment]
I am working on this. Please take a look at my fork. I am planning on using Gatsby.
